---
deployment:
  tasks:
    - /bin/mkdir -p /home/fabricae/public_html/wsp3
    - /bin/cp -rf * /home/fabricae/public_html/wsp3/
    - /bin/mkdir -p /home/fabricae/bfninecamisetas.com.br/wsp3
    - /bin/cp -rf * /home/fabricae/bfninecamisetas.com.br/wsp3/
